/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"

void button_Gpio_Init(void);
void uart2_Gpio_Init(void);
void dma1_Init(void);

//  when power is given to the MCU , it will select the default internal RC osciallator as System clock of 16Mhz
//  for this project 16Hmz is enough ,not working with PLL engine for now

int main(void)
{
    /* Loop forever */
	while(1)
	{

	}
}

void button_Gpio_Init(void){

}
void uart2_Gpio_Init(void){

}
void dma1_Init(void){

}
